import CONFIG from '../config';

const SYSTEM_PROMPT_QUESTIONS = `You are Spec Architect, an expert software product specification assistant.
When a user provides an idea, generate exactly 3-5 clarifying questions focused on:
1. Problem: What specific problem does this solve?
2. User: Who is the target user/audience?
3. Scope: What is in-scope and out-of-scope for v1?
4. Constraints: Technical, time, resource, or compliance constraints?
5. Success: How will success be measured?

Return ONLY a valid JSON array of question strings. No explanation, no markdown.
Example: ["What specific problem...", "Who is the primary user...", "What features are in scope..."]`;

const SYSTEM_PROMPT_SPEC = `You are Spec Architect, a world-class technical specification writer.
Given a user's idea and their answers to clarifying questions, produce a comprehensive Project Spec Sheet in Markdown.

Structure:
# Project Spec Sheet: [Project Name]
## Executive Summary
## Problem Statement
## Target Users
## Solution Overview
## Feature Scope (v1)
### In Scope
### Out of Scope
## Technical Requirements
### Architecture
### Tech Stack
### APIs & Integrations
## Constraints & Assumptions
## Success Metrics
## Risk Analysis
| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
## Timeline Estimate
---
*Generated by Spec Architect*`;

async function callGemini(systemPrompt, userMessage) {
    const url = `${CONFIG.GEMINI_BASE_URL}/models/${CONFIG.GEMINI_MODEL}:generateContent?key=${CONFIG.GEMINI_API_KEY}`;
    const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            contents: [{ role: 'user', parts: [{ text: `${systemPrompt}\n\nUser Input:\n${userMessage}` }] }],
            generationConfig: { temperature: 0.7, maxOutputTokens: 4096 },
        }),
    });
    if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err?.error?.message || `Gemini API hatası: ${response.status}`);
    }
    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
}

async function callOpenAICompatible(systemPrompt, userMessage, provider) {
    const isGroq = provider === 'groq';
    const baseUrl = isGroq ? CONFIG.GROQ_BASE_URL : CONFIG.OPENAI_BASE_URL;
    const apiKey = isGroq ? CONFIG.GROQ_API_KEY : CONFIG.OPENAI_API_KEY;
    const model = isGroq ? CONFIG.GROQ_MODEL : CONFIG.OPENAI_MODEL;

    const response = await fetch(`${baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
            model: model,
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userMessage },
            ],
            temperature: 0.7,
            max_tokens: 4096,
        }),
    });
    if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err?.error?.message || `${isGroq ? 'Groq' : 'OpenAI'} API hatası: ${response.status}`);
    }
    const data = await response.json();
    return data.choices?.[0]?.message?.content || '';
}

function callAI(systemPrompt, userMessage) {
    if (CONFIG.AI_PROVIDER === 'openai' || CONFIG.AI_PROVIDER === 'groq') {
        return callOpenAICompatible(systemPrompt, userMessage, CONFIG.AI_PROVIDER);
    }
    return callGemini(systemPrompt, userMessage);
}

function isDemoMode() {
    let key = CONFIG.GEMINI_API_KEY;
    if (CONFIG.AI_PROVIDER === 'openai') key = CONFIG.OPENAI_API_KEY;
    if (CONFIG.AI_PROVIDER === 'groq') key = CONFIG.GROQ_API_KEY;
    return !key || key.startsWith('your_') || key.length < 10;
}

export async function generateQuestions(idea) {
    if (!idea || !idea.trim()) throw new Error('Lütfen önce bir fikir yazın.');

    if (isDemoMode()) {
        return [
            'Bu fikrin çözmeye çalıştığı spesifik problem nedir ve bu sorunu kimler yaşıyor?',
            'Hedef kullanıcın kim? Demografisini, teknik bilgi seviyesini ve temel sorununu tanımla.',
            'İlk sürümde (MVP) kesinlikle olması gereken 3 temel özellik nedir?',
            'Teknik, bütçe veya zaman kısıtların var mı?',
            'Başarıyı nasıl ölçeceksin? 3 ay sonra "çalıştı" demek ne anlama gelir?',
        ];
    }

    const rawText = await callAI(SYSTEM_PROMPT_QUESTIONS, idea);
    const jsonMatch = rawText.match(/\[[\s\S]*\]/);
    if (!jsonMatch) throw new Error('AI beklenmedik bir format döndürdü. Tekrar dene.');
    const questions = JSON.parse(jsonMatch[0]);
    if (!Array.isArray(questions) || questions.length < 3) throw new Error('AI yeterli soru üretemedi. Tekrar dene.');
    return questions.slice(0, CONFIG.MAX_QUESTIONS);
}

export async function generateSpecSheet(idea, questionsWithAnswers) {
    const qaBlock = questionsWithAnswers
        .map((qa, i) => `S${i + 1}: ${qa.question}\nC: ${qa.answer}`)
        .join('\n\n');
    const userMessage = `Fikir:\n${idea}\n\nNetleştirme S&C:\n${qaBlock}`;

    if (isDemoMode()) {
        return `# Project Spec Sheet: ${idea.substring(0, 50)}

## Executive Summary
Bu proje, keşif sürecinde belirlenen temel kullanıcı ihtiyacını karşılamaktadır. Çözüm, net sınırlara ve ölçülebilir hedeflere sahip, odaklı bir v1 ürün sunar.

## Problem Statement
${questionsWithAnswers[0]?.answer || 'Kullanıcı araştırmasına göre tanımlanacak.'}

## Target Users
${questionsWithAnswers[1]?.answer || 'Birincil kullanıcılar tanımlanacak.'}

## Solution Overview
Netleştirme süreciyle doğrulanan minimal, yüksek etkili özellik setiyle temel sorunu ele alan dijital bir ürün.

## Feature Scope (v1)
### In Scope
- ${questionsWithAnswers[2]?.answer || 'Temel özellik 1'}
- Kullanıcı onboarding akışı
- Temel bildirim sistemi

### Out of Scope
- Gelişmiş analitik (v2)
- Üçüncü taraf entegrasyonlar (v2)

## Technical Requirements
### Architecture
REST API backend ile istemci-sunucu mimarisi.

### Tech Stack
- Frontend: React Native (Expo)
- Backend: Node.js / Express
- Database: PostgreSQL
- Hosting: AWS / Vercel

### APIs & Integrations
- Kimlik doğrulama sağlayıcı
- Push bildirimler

## Constraints & Assumptions
${questionsWithAnswers[3]?.answer || '- 3 aylık süre\n- Küçük ekip\n- Sınırlı bütçe'}

## Success Metrics
${questionsWithAnswers[4]?.answer || '- 1. ayda 100 aktif kullanıcı\n- <2s yükleme süresi\n- >4.0 uygulama mağazası puanı'}

## Risk Analysis
| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
| Kapsam kayması | Yüksek | Yüksek | Sıkı v1 sınır yönetimi |
| Düşük benimseme | Orta | Yüksek | Erken kullanıcı testi |
| Teknik borç | Orta | Orta | Kod incelemeleri |

## Timeline Estimate
- 1-2. Hafta: Tasarım & Mimari
- 3-6. Hafta: Geliştirme
- 7-8. Hafta: Test & QA
- 9-10. Hafta: Beta Yayın
- 11-12. Hafta: İterasyon & v1 Yayın

---
*Generated by Spec Architect · Demo Modu · ${new Date().toLocaleDateString('tr-TR')}*`;
    }

    return callAI(SYSTEM_PROMPT_SPEC, userMessage);
}
